version: '3.9'

services:
  antonioconselheiro-dev:
    image: antonioconselheiro-dev
    container_name: antonioconselheiro-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /antonioconselheiro
    volumes:
      - ..:/antonioconselheiro:cached
    tty: true
