version: '3.9'

volumes:
  node_modules_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules

services:
  antonioconselheiro-dev:
    image: antonioconselheiro-dev
    container_name: antonioconselheiro-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /antonioconselheiro
    volumes:
      - ..:/antonioconselheiro:cached
    tty: true
